set(CMAKE_SYSTEM_NAME Linux)

set(CM4_TOOLCHAIN_PREFIX "$ENV{CM4_TOOLCHAIN_PREFIX}" CACHE STRING "Toolchain triplet prefix")
if(NOT CM4_TOOLCHAIN_PREFIX)
    set(CM4_TOOLCHAIN_PREFIX "aarch64-linux-gnu" CACHE STRING "Toolchain triplet prefix" FORCE)
endif()

set(CMAKE_C_COMPILER "${CM4_TOOLCHAIN_PREFIX}-gcc" CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${CM4_TOOLCHAIN_PREFIX}-g++" CACHE FILEPATH "C++ compiler")

set(CMAKE_SYSROOT "$ENV{CM4_SYSROOT}" CACHE PATH "Sysroot for Compute Module 4")
if(CMAKE_SYSROOT)
    set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
